### PR TITLE
Add instructions for manual setup in README.md.

### PR DESCRIPTION
**Pull request by ryanchangx**
Add instruction to readme to allow devs to setup the environment quickly using manual commands.

Also cleaned up unnecessary build files (whcih are generated from mvn clean install).

### CODE REVIEW

**Review by Charles-Hong520 — APPROVED** [review]
good pr

**Review by KunalMittal322 — APPROVED** [review]
👍

**Review by Qrooz — APPROVED** [review]
Nice!

**Review by KunalMittal322 — APPROVED** [review]

**Review by KunalMittal322 — APPROVED** [review]
A

**Pull request merged**
